### ISSUE TITLE
Spell Casting Not Working

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#1953]
Oftentimes, when I do a click combo to cast a spell (Right-Right-Left, etc), it simply displays the combo on the screen, without casting a spell, just like when on a horse. Might be a lag problem.

**Comment by epicman739** [comment]
This is probably a lag-based issue.

**Comment by Trixter313** [comment]
If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by Penguinepowadude** [comment]
This issue still occurs. It happens even if I am not experiencing lag issues.

**Comment by Trixter313** [comment]
Hmm, this is an odd issue indeed. If it's been awhile since you've restarted your router and/or computer, maybe try doing that. Other than that I'm not sure there's much more we 'normals' can do about it and a staff member might need to get involved. They check here periodically so if it doesn't get fixed on it's own someone should see it eventually. :)
