### ISSUE TITLE
Known issues since yesterday's server maintenance...

### ISSUE THREAD

**Issue by Jamdog** [Wynncraft/Issues#2160]
1) It now rains in Wynn.  There have even been reports of thunderstorms!
![2015-08-01_15 42 47](https://cloud.githubusercontent.com/assets/94101/9022194/028a0964-3864-11e5-9b1e-92a35ac70858.png)

2) Players are able to put items into item frames, although they can't get them back out.  One person has already lost a Bob's Mythic item in the Emerald item frames above the door to Detlas Bank ([Forum thread](https://forums.wynncraft.com/threads/86254/)). 
![cc2csmw](https://cloud.githubusercontent.com/assets/94101/9022397/a636e5a8-386b-11e5-8d8e-131b488802d0.png)
Players can also rotate items in the frames.
![2015-08-01_15 59 19](https://cloud.githubusercontent.com/assets/94101/9022243/569c5668-3866-11e5-9887-220b0c884cc7.png)

3) Firetick appears to be enabled.  Ice can melt near flames/glowstone.  Nivla Woods has not yet burned down, but it's only a matter of time..
Bob's Tomb is full of holes:.
![2015-08-01_15 53 55](https://cloud.githubusercontent.com/assets/94101/9022230/914473fa-3865-11e5-9175-95833975adb0.png)
And this may give players access to places they couldn't normally go, and allow them to get stuck, such as in this cave behind the ToA:
![2015-08-01_16 45 35](https://cloud.githubusercontent.com/assets/94101/9022435/293d3000-386d-11e5-92b3-6354e96dcb9f.png)

4) All server signs in lobby report 0/100 players, and cannot be clicked on to enter the server
![2015-08-01_15 41 37](https://cloud.githubusercontent.com/assets/94101/9022190/d86195d0-3863-11e5-9d9a-d87a4d99bda1.png)

5) The server selection in lobby (inventory) often shows there are more than the max number of players in a server.  For example:
![2015-08-01_15 38 33](https://cloud.githubusercontent.com/assets/94101/9022258/b90aca5a-3866-11e5-8a25-28e90c337179.png)
Also, trying to connect to servers often says that they are full regardless of whether they show in the server selection as full or not...

6) The **/find** command reports that players are on a server when they are not.

7) The Creeper Guard in the Creeper Cave is now free-roaming, and can be pushed out of the cave by a player
![2015-08-01_16 30 36](https://cloud.githubusercontent.com/assets/94101/9022377/e220b752-386a-11e5-91f6-37415898210b.png)

8) TNT now explodes, but does no damage (just the TNT is no longer there).  Before the update, it would simply vanish - there would be no explosion.  [See Video](http://youtu.be/Q2kQJeb-klQ)

9) When trying to connect to a server from the lobby, some players are getting a message saying that they are already logged in to the server:
![already](https://cloud.githubusercontent.com/assets/94101/9022738/32bd4adc-3879-11e5-8e7a-9d8364db952c.png)

**Comment by Trixter313** [comment]
I believe all of the item frame issues have been fixed.

**Comment by Moe-Ronickah** [comment]
Not all, Trixter.  Someone is still missing a Mythic Bow, but a ticket has been opened with support.

**Comment by Trixter313** [comment]
But the actual issue is resolved, correct? No one can put items in item frames or rotate items any more, as far as I can tell.

Also #5 about servers showing more players than the max seems to no longer be happening.

#6 is hard to tell but I've tried it and it seems to be functioning correctly now.

I'm guessing #8 is on the build server so no way of telling whether it still happens or not.

I've seen reports of #9 and experienced it before the maintenance so I don't think the maintenance caused it.

**Comment by Moe-Ronickah** [comment]
I've tested all of the frames in Detlas in several servers, and the maps (empty handed), and they all appear to be fixed.  They all have proper names and none can be interacted with, now, so I believe that the permissions for the frames are fixed.

Firetick appears to be off, as all of the frozen lands, and Bob's Tomb, are back to normal, that is, no flowing water and no melted floors.

**/find** works for me, and I've heard no comments about it.

I've been through Pigman Valley, and seen no signs of wandering Creeper Guards.

# 8 I've never seen.

I agree with having seen # 9, before, however, I think is was greatly worse during maintenance, but not since then.
