### ISSUE TITLE
Not being able to connect to world

### ISSUE THREAD

**Issue by Ziggybon** [Wynncraft/Issues#2169]
When I try to connect to worlds it puts me back in the hub and says I'm already connected to that world, even though I'm definetly not because I'm still in the hub. I also reïnstalled MC and everything.
![2015-08-04_21 24 48](https://cloud.githubusercontent.com/assets/13648173/9070320/46dea326-3aef-11e5-84f9-368a8af71f65.png)

**Comment by Ziggybon** [comment]
It kind of fixed itself so idk, it seems like its fixedd anyway

**Comment by Trixter313** [comment]
Whenever someone has this issue it usually ends up fixing itself with a little bit of time.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thanks and we hope you enjoy your time playing Wynncraft! :)

**Comment by Ziggybon** [comment]
yeahh umm, the issue came back, it seems that I can sometimes connect to one of the worlds but now it mostly doesn't work anymore

**Comment by Trixter313** [comment]
I see that you are using a mod(s). Have you tried logging in using vanilla Minecraft? Many users have been experiencing difficulties logging in lately with any type of mods or mod loaders installed.
