### ISSUE TITLE
Hole with 3x1x2 block hole with water in under potion shop outside Main City

### ISSUE THREAD

**Issue by MCninja011** [Wynncraft/Issues#2302]
There was a button at the end of the path and I went in and got trapped. Can anyone help?
![2015-09-15_20 50 32](https://cloud.githubusercontent.com/assets/14303906/9893991/e4ddde66-5bec-11e5-9556-ed9ed6154a19.png)   
![2015-09-15_20 50 36](https://cloud.githubusercontent.com/assets/14303906/9894015/e7fe2466-5bec-11e5-9c37-f190c6307a52.png) 

Please Help thanks

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points will teleport you to the nearest visited town.

If your issue is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by TrashcanMan** [comment]
Wait the sewer exit is STILL broken? How long has it been?

**Comment by MCninja011** [comment]
Yeah the sewer exit is still broken, but i dont know how long it has been.

**Comment by TrashcanMan** [comment]
From what I know it's been at least a month or two.
