### ISSUE TITLE
Im stuck in a prison cell within llevigar

### ISSUE THREAD

**Issue by MATTCFTW** [Wynncraft/Issues#2695]
i dont know if this is too do with a quest or not, but if it is i haven't started the quest.

**Comment by Trixter313** [comment]
Typing /kill with 3+ soul points should teleport you to the nearest visited town.

If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by brainscript** [comment]
@MATTCFTW I would reopen it. This is not fixed! I went into the prison visiting room and then through the exit door. After going through a corridor I got **TELEPORTED** into the cell. There's no way to exit unless doing `/kill`. *I've got so many deaths in my stats because of "bugs" like this ...* :disappointed:
