### ISSUE TITLE
[Not working] Can't select a class

### ISSUE THREAD

**Issue by Verret001** [Wynncraft/Issues#3139]
**NEW ONE: https://github.com/Wynncraft/Issues/issues/3250**

I had posted this 3 days ago but it got closed in the gravel clean. 
This issue is still not fixed, 
My level 42 mage seems to be unable to load, Ive joined multiple servers but it refuses to load at all. All I get when i load mage is "There has been a error, try again"

There are also errors when loading archer, this has not happened to
me but has happened to enough people to know its not a hoax

This is what It looks like: 
https://youtu.be/NpyLuoczjBc

**Comment by Verret001** [comment]
Although these were closed in the gravel update these are some cases;
https://github.com/Wynncraft/Issues/issues/3006
https://github.com/Wynncraft/Issues/issues/3059

**Comment by Verret001** [comment]
**UPDATE**
This still isn't fixed, Exact same thing continues to happen, This is what I have to say to it; 
:fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: 
:hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: :hankey: 
:fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu: :fu:

**Comment by survivalmonkney** [comment]
I have the same problem, I can't get into my L53 archer, it has the same error every time i try to join. Doesn't work on any servers after relogging and rebooting. 

Is there anything weird with the stats for anyone, like my archer has 112% XP?

**Comment by DarkDemonDragon** [comment]
Is this bug still persisting?

**Comment by survivalmonkney** [comment]
No, I think I got into my archer class a few weeks ago, but I already had another archer that was 10 levels higher, so I deleted it.

**Comment by DarkDemonDragon** [comment]
@Verret001 is this issue still persistin for you?

**Comment by lkjfdsaofmc** [comment]
Idk about Verret @DarkDemonDragon, but i'm still having the issue.

**Comment by Verret001** [comment]
This issue is fixed.

**Comment by SkaiiZ** [comment]
This issue is still not fixed for me, and here are screenshots.

[https://gyazo.com/0e1cbfef36aa2d57108a0895190d945c](url)

**Comment by Moe-Ronickah** [comment]
@SkaiiZ , please open a new issue, and describe in detail what is happening to you.  Your screenshot does not match the original issue, here, at all.

**Comment by BoostedAnimal69** [comment]
This issue is happening to me i can't load my warrior. I get the error "There has been a error...try again" Please help!

**Comment by LordHelmchen98** [comment]
@BoostedAnimal69 read the messages on #7185 for more information.
