### ISSUE TITLE
Flight in Distress/Acquring Credentials issue

### ISSUE THREAD

**Issue by awemanrank100** [Wynncraft/Issues#3343]
The Untradable "Dusty Passport" that you get from the Lost and Found area can be used to start Flight in Distress. As I was waiting for a triple exp server, and had the passport on me, I walked around and ended up talking to the flight attendant, who accepted the passport. Upon completing Acquiring Credentials, I am given the Quest Item version of it, yet it does not do anything due to me having already started the quest. An additional lore detection will probably be needed to fix this.

![](http://i.imgur.com/IN9AjY4.png)
![2015-12-29_22 24 32](https://cloud.githubusercontent.com/assets/9545223/12047100/0594bb76-ae7b-11e5-92bd-731c922176d5.png)

**Comment by HeyloLP** [comment]
jump on the big are ship and then outside at the back

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by awemanrank100** [comment]
I still have that Dusty Passport Quest Item taking up space. :I

**Comment by Trixter313** [comment]
I've never done the quest personally, but are you sure you aren't supposed to have it in the end? Some quests have items that you use in later quests or for future, to-be made quests.

**Comment by DarkDemonDragon** [comment]
@Trixter313 no you are not supposed to have that in the end.

@awemanrank100 I'm pretty sure you can throw it away. If you cannot throw it away because it gives you the red text saying: "You'll need this item for future quests" then during the daily chest place the dusty passport in the chest GUI and then exit out. The item will then disappear. Be careful you don't accidentally place another item in the chest GUI as it will permanently delete it.
