### ISSUE TITLE
Missing Capital Letter on Merchant

### ISSUE THREAD

**Issue by HeyItsMeTom** [Wynncraft/Issues#3389]
At 1018 9 -1938, there's a merchant called "emerald Merchant" (without a capital letter on the e). As a grammar nazi I couldn't help but cry because of this.

**Comment by Trixter313** [comment]
Apparently there are actually 3 "emerald Merchants", all in the Almuj bank.

**Comment by AckroWynn** [comment]
Fixed. @Trixter313

**Comment by Trixter313** [comment]
@AckroWynn do you know when this will show in the server? As of right now, they are still incorrect. Thanks!

**Comment by AckroWynn** [comment]
@Trixter313 That depends on when the next map push is. Expect a fix being deployed in **at most** 30 days.

**Comment by Trixter313** [comment]
Ok, great. Thanks!
