### ISSUE TITLE
Glitching? (Can't join)

### ISSUE THREAD

**Issue by JellyQuagga** [Wynncraft/Issues#3685]
So basically I can't play Wynncraft anymore. I don't know how to explain so here is a photo of the chat every time I tried to play:
<img width="826" alt="wynncraft" src="https://cloud.githubusercontent.com/assets/16699084/12318194/9accb6e4-baec-11e5-8d58-b30fcce8fee4.PNG">

I think it was because I used "Escape" as an archer and while I was in the middle of the air I left? I don't remembered if I did that or not... Worst, I put /toggle autojoin so I can't really do much anymore.
Can someone please help me? (If you can)

**Comment by icninja** [comment]
I'm having the same issue, but i think i logged out while on a half block or something like that. I am getting the same message, and i also have /toggle autojoin on as well. I'm a level 59 assassin if that info helps..

**Comment by DarkDemonDragon** [comment]
When you spawn in hold SHIFT. If this doesn't work after a couple tries first do /kill while in the lobby. Then spawn into a world. When you spawn in quickly press: "t" "up arrow" "enter" to kill yourself before you can be kicked. Of course don't do this if you have less than 3 SP on your Archer.

**Comment by Dar-krusos** [comment]
I am having the same issue, and I can assure you that I was standing on a full block and not midair when I logged out last. You are kicked too fast to be able to /kill and if it's not too fast for me, it's freezing anyway or just says "Please go into a game world to use commands!" (this is due to me having to select a class every time, supposedly due to my slower internet speed). The problem may be with my net speed, or two other things that I can think of, which are that they have brought in better fly protection or they've made it so we're spawning higher than usual (maybe so we don't get stuck in blocks when we log in all the time).

**Comment by TheStallker** [comment]
I am having the same probleme...

**Comment by Dar-krusos** [comment]
I've been told that fly-kicks were re-enabled, but something may have gone wrong in the process (maybe they were trying to upgrade it).

**Comment by xElitaa** [comment]
Same problem here..

**Comment by sarah7272665** [comment]
Same problem over here >.<

**Comment by sarah7272665** [comment]
Fixed it by holding down one of the wasd keys when I spawned so I moved off the half block

**Comment by tolin99** [comment]
Yeah I got the same problem...

**Comment by Trixter313** [comment]
So are people still experiencing this or did the suggestions in this thread fix the problem? Thanks!

**Comment by Dar-krusos** [comment]
I'm pretty sure they fixed it already, so it will only occur from major lag now.

**Comment by Trixter313** [comment]
Ok, until some says otherwise I will close this issue then.
