### ISSUE TITLE
Shattered minds quest problem

### ISSUE THREAD

**Issue by Aurorynx** [Wynncraft/Issues#3741]
When I'm in the acid trip version of Efelim, my quest book says to find it (which I did) so I tried talking to Likeru(?) But she jumps straight to a 1 liner response and my quest book doesn't update. I can't venture further into the quest until she actually says more than 1 line!

**Comment by Dar-krusos** [comment]
What does your Quest Book say?

**Comment by Troll2828** [comment]
Go back to where you spawn when you enter the acid trip version of Efelim. Then, follow the arrows that guide you to Efelim. Maybe there was lag so you didn't trigger something

**Comment by Trixter313** [comment]
If your problem is now resolved, we'd appreciate it if you closed this issue. If it's not, we'd be happy to continue to assist you as much as possible. Thank you and we hope you enjoy your time playing Wynncraft! :)

**Comment by Aurorynx** [comment]
I re-did went back to do the acidtrip Efelim the next day and it still wont work. "Try and find civilisation with the strange forest" it still says, and Likeru(?) is still saying 1 liners

**Comment by Dar-krusos** [comment]
Try following the road that leads to the village, and if that still doesn't work, maybe you dropped the mushrooms.

**Comment by Trixter313** [comment]
Try following along with this video to make sure you're doing it correctly: https://www.youtube.com/watch?v=nwk9pDSO74U

**Comment by Moe-Ronickah** [comment]
Aurorynx, there was a map update on Feb 18.  Is your issue resolved or is it still ongoing?

**Comment by Aurorynx** [comment]
I'll do it again to see if it'll let me through

**Comment by Trixter313** [comment]
Is your issue now resolved?

**Comment by Moe-Ronickah** [comment]
60+ days without a negative response, so I'm closing this as fixed.
