### ISSUE TITLE
Nemract bank

### ISSUE THREAD

**Issue by Mario1230X** [Wynncraft/Issues#3953]
Logging out in nemract bank, then rejoining as that class causes you to get a "You are not allowed to enter this area" Message then you are teleported to the class select room. I got Ganny to help me out, but the only other way is /kill.

**Comment by Moe-Ronickah** [comment]
This problem was also happening in Llevigar several days ago, and then in either Nemract, or just Nemract bank, as you have reported.  I believe that the problem was fixed that same day.  If you are no longer having this problem, would you please close this issue?  Thank you.

**Comment by Mario1230X** [comment]
It is not fixed. there was an update today so I'll check but I'm freaking
level one because all my classes got deleted.


On Saturday, February 6, 2016, Moe-Ronickah <notifications@github.com>
wrote:

> This problem was also happening in Llevigar several days ago, and then in
> either Nemract, or just Nemract bank, as you have reported. I believe that
> the problem was fixed that same day. If you are no longer having this
> problem, would you please close this issue? Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/3953#issuecomment-180781690>.
>


-- 
Buy lenny protection for 999$ today for an extra 5% off! (+ tax and
shipping).
╰( ͡° ͜ʖ ͡° )/
....../▌

░░░░░███████ ]▄▄▄▄▄▄▄▄  - - pew pew
▂▄▅█████████▅▄▃▂
Il███████████████████].
◥⊙▲⊙▲⊙▲⊙▲⊙▲⊙▲⊙◤..
LENNY'S TRUE FORM.
╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ(∩ ͡ ° ʖ ͡ °) ⊃-(===> (⌐□_□) MLG
NOTHING BREAKS THE ATTACKS!

**Comment by Moe-Ronickah** [comment]
Mario, is this fixed for you?

**Comment by Mario1230X** [comment]
I will have to check later, cant get on right now.

On Wed, Feb 10, 2016 at 4:30 PM, Moe-Ronickah <notifications@github.com>
wrote:

> Mario, is this fixed for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Wynncraft/Issues/issues/3953#issuecomment-182607876>.
>



-- 
Buy lenny protection for 999$ today for an extra 5% off! (+ tax and
shipping).
╰( ͡° ͜ʖ ͡° )/
....../▌

░░░░░███████ ]▄▄▄▄▄▄▄▄  - - pew pew
▂▄▅█████████▅▄▃▂
Il███████████████████].
◥⊙▲⊙▲⊙▲⊙▲⊙▲⊙▲⊙◤..
LENNY'S TRUE FORM.
╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ(∩ ͡ ° ʖ ͡ °) ⊃-(===> (⌐□_□) MLG
NOTHING BREAKS THE ATTACKS!

**Comment by Trixter313** [comment]
I believe this is fixed. If not, simply comment and I'll reopen the issue. Thank you!

**Comment by DebugMC** [comment]
It is fixed (Mario was me long ago actually :D I was Mario1230X) It also can teleport you to... uh... thats something ill tell a mod somewhere else...
