### ISSUE TITLE
Vampire bats missing texture

### ISSUE THREAD

**Issue by aramaril** [Wynncraft/Issues#4066]
Vampire bats just outside of the Jungle Village heading into Dernel Jungle have attacks that are missing textures. They appear as boxes of pink and black squares.
![mistex2](https://cloud.githubusercontent.com/assets/17123618/12947389/81760c02-cfc0-11e5-86cc-54daedf5d3d5.png)

**Comment by Trixter313** [comment]
Is this still happening to you?

**Comment by aramaril** [comment]
yes it is still broken.
![still broke](https://cloud.githubusercontent.com/assets/17123618/13026234/eef9cdb4-d1e5-11e5-8a57-7d7aa9cbacbd.png)

**Comment by aramaril** [comment]
the cavern bats in the desert region are also equally shooting the pink and black boxes. i don't have a screen shot of this though as they don't seem to be re spawning for some reason. its the exact same issue though so I'm hoping you wont need to have a screenshot.

**Comment by aramaril** [comment]
oh i guess dead cowboys also have these boxes got a screen pick for that though
![dead cowboy](https://cloud.githubusercontent.com/assets/17123618/13026703/315f2cd8-d1f7-11e5-9fc9-95c58b344f93.png)

**Comment by BlahBlah161616** [comment]
Same for me

**Comment by Dar-krusos** [comment]
Yeah, it's always been this way since the resource pack was implemented. The people that worked on the textures have just got to add some.

**Comment by Moe-Ronickah** [comment]
Dar, do you have information from a reliable source that the missing textures are indeed being added?

**Comment by Dar-krusos** [comment]
No, I just said that they need to add them.

**Comment by Moe-Ronickah** [comment]
Is this still happening?  Can anyone check on these while wandering around and remember to let us know, here, so that we can close whatever is fixed?

**Comment by Moe-Ronickah** [comment]
It's still not fixed.  Bats throw whositwhatsit balls.

**Comment by Villageacules** [comment]
Fixed during Gameplay update, closed.

**Comment by DebugMC** [comment]
@Villageacules its not fixed, they are now bats, but they fire huge missing texture still.
