### ISSUE TITLE
Skill points resetting causing accessories/armor to unequip

### ISSUE THREAD

**Issue by TheDollarBill** [Wynncraft/Issues#4120]
I logged onto my archer and my chat was spammed with "[Accessory] requires your agility to be at least level X" despite my agility level being over 100. My accessories were forced out of my inventory and onto the floor because my inventory was full. **I'm not asking for any refunds**, but I lost my Jester Bracelet due to this. Here's a screenshot of the bug: http://i.imgur.com/iKdutaN.png

**Comment by pewpeed** [comment]
I logged onto my warrior and it happened again: http://i.imgur.com/CB4EsLp.png
http://i.imgur.com/eHKEl0N.png

I'm not sure how to replicate the bug...

**Comment by pewpeed** [comment]
Happened a third time http://i.imgur.com/V27brGq.png

**Comment by pewpeed** [comment]
Happened a FOURTH time... lost my near max walk speed Contrail and max walk speed Autotomized http://i.imgur.com/2BO2uwt.png

**Comment by pewpeed** [comment]
5th time, lost my new Contrail http://i.imgur.com/scMS3y5.png

**Comment by Trixter313** [comment]
Could you post screenshots of each classes skill points menu that was affected? Thanks!

**Comment by pewpeed** [comment]
Archer: http://i.imgur.com/S3zf57f.png
Warrior: http://i.imgur.com/nyJNORJ.png

**Comment by ThunderRemix** [comment]
Yeah, this has also happened to me.

**Comment by Moderocky** [comment]
Happens to me every time I log into a guild war (all my armour does as well), I've never had it happen on login though. I think this is the same issue.

**Comment by TheDollarBill** [comment]
Happened a 6th time, notice the accessories are in the wrong locations for some reason... http://i.imgur.com/Zu99ug1.png

**Comment by TheDollarBill** [comment]
Happened again, and I've been noticing that when the accessories are forced out of my inventory, they don't appear next to me, but rather they flew all the way up to the roof (I was standing inside Cinfras bank when this happened) http://i.imgur.com/qxrTxaB.jpg

**Comment by Moderocky** [comment]
Yep. Just lost 2* legendary Precious ring.

**Comment by TheDollarBill** [comment]
Once again... http://i.imgur.com/SCVFR6H.png
My stats without the bracelet: http://i.imgur.com/0CHAWYk.png

**Comment by Odnod** [comment]
My best guess is that this happens because of lag similar to the 'kicked for flying' errors.

**Comment by thecoolkogut4** [comment]
i had the same problem. i used a skill reset scroll with a full inv. i was wearing armour and accessories with skill point req, i had a full inv and the items vanished into thin air. i hope this gets resolved.

**Comment by TheDollarBill** [comment]
Yay! Just lost 33% XP Jester Bracelet :/

**Comment by TheDollarBill** [comment]
I managed to screenshot my X'd out stat requirements on my Jester Bracelet for a brief moment after I logged in, even though I had the correct stat requirements:

X'd out stats req. on bracelet: http://i.imgur.com/vwdamjy.png
My stats: http://i.imgur.com/rfAqtZq.png

**Comment by thecoolkogut4** [comment]
ik what your going through, i lost 2 jester bracelets, 1 speaker, 1 aries... probably gonna lose more. hopefully this will be in the .10 patch

**Comment by Moderocky** [comment]
I have worked out why. (Mostly)
Sometimes you'll notice in your inventory that randomly your armour's name will be in italics and the lore will just turn to a big purple string. This means that the stats go (it goes back to normal after a few seconds). Obviously you lose the extra stats but it isn't a problem mostly as your rings also glitch in the same way.

Sometimes only part of your armour glitches, you lose your stats and it throws all your stuff halfway across the map. ;-;

**Comment by gettodachopa** [comment]
x2, this needs to be fixed fast, I lost many items this way, (my inventories are full with quests items)

**Comment by Moderocky** [comment]
I usually store all my quest items in another character. After all; if you can't find one later on you can /fixquests to get it back :+1:

**Comment by DarkDemonDragon** [comment]
I made a thread on the forums, and a portion of the issue has been fixed by Salted. Now when you don't fit the requirements and your inventory is full your items will drop by you instead of Bob knows where. Hopefully this means no more random bouts of players losing their gear. If no one reports experiencing this issue within the next 20 days then this bug will be confirmed to be resolved and closed.

**Comment by DarkDemonDragon** [comment]
Thread Link: https://forums.wynncraft.com/threads/this-bug-needs-to-be-aknowledged.113507/

**Comment by Odnod** [comment]
@darkdemondragon this is a different vug entirely from that one, and I believe this one has to do exclusively with player or server side lag.

**Comment by DarkDemonDragon** [comment]
@Odnod Which link? My thread or the reference? The reference is 100% this bug 
**This:** "My accessories were forced out of my inventory"
**That:** "This caused some of my gear to pop off"

**Comment by Odnod** [comment]
@DarkDemonDragon the reference is about a different bug that surfaced yesterday in which you could not use weapons, you took no damage, and your soul points were set to 0. I believe it has since been fixed. This bug does not originate from all stats being set to 0, and while similar in nature to the other one it is an older and different bug.

**Comment by DarkDemonDragon** [comment]
@Odnod please reread the reference. Nowhere does he mention SP, damage, or weapon usage. This is 100% a duplicate of this. 

Stats being 0 is his interpretation of the issue which may or may not be true.

**Comment by Odnod** [comment]
He states specifically within the thread that all of his skill points were set to 0. (I have been referring to #4241) Anyway I see no reason to get too worked up about this. It could be the same bug, it could not be. I was just pointing out a potential error.

**Comment by DarkDemonDragon** [comment]
@Odnod I'm just saying that his issue stems from this and is a duplicate

**Comment by TheDollarBill** [comment]
I can confirm that the items DO NOT drop on the ground when your inventory is full. I lost a Sagittarius and ALL of my walk speed accessories... thanks Salted
Nothing on the ground and chat log: http://i.imgur.com/zA83PX5.png
My (full) inventory: http://i.imgur.com/Z4uwZJS.png

**Comment by Trixter313** [comment]
@TheDollarBill if this happens again, could you check your skill points as fast as possible and post a screenshot here? That way we can tell whether this is caused by skill points randomly being reset to 0 or if it's a separate issue. Thanks!

**Comment by TheDollarBill** [comment]
The first few times this glitch happened to me, the 0 skill points glitch didn't occur as I was able to reequip the accessories without having to relog to fix my skill points. I've been affected by two different unequipping glitches here, one where the armor/accessories simply unequip upon log in and one where the skill points are reset upon log in, thus equipping the armor/accessories. These two glitches are probably related due to them both occurring upon log in.

**Comment by DarkDemonDragon** [comment]
@TheDollarBill that is 1 bug. When you have 0 skill points you won't be able to wear armor with skill requirements. This is why they fall off.

**Comment by TheDollarBill** [comment]
When this bug initially happened to me (when I first posted this issue), my skill points were not set to 0. The issue was that the accessories simply unequipped randomly, not because of the skill points.

**Comment by TheDollarBill** [comment]
Now that I think about it again, yeah, it is pretty much the same issue. It's just that one glitch sets your skill points to 0 for a brief moment after you log in while the other one sets it to 0 until you relog.

**Comment by Moe-Ronickah** [comment]
This issue is still alive.

**Comment by EvilPiggy** [comment]
Yup, i got it now. I'm VERY lucky my inv wasnt full! phew!

**Comment by TheDollarBill** [comment]
@Trixter313 if you still want a screenshot of my stats right after the glitch happened: https://i.imgur.com/wwfrsfv.png

**Comment by Kanoku108** [comment]
I couldn't screenshot my problem as it was instantaneous. I logged on and saw all my gear besides leggings on the floor and my skill points where reset I was grinding and died instantly since I was basically naked. I don't mind losing armor since it's fairly easy to recover but precaution on this glitch should be taken.

**Comment by TheDollarBill** [comment]
Apparently, this glitch also makes you invincible: https://i.imgur.com/iDgrJUX.png (notice the 2220/2220 health)

**Comment by thecoolkogut4** [comment]
it didint make you invincible right when the bug came out, i think they added that in so you dont die and you can pick your armour back up. (im not 100% sure but thats what i think)

**Comment by YunoFGasai** [comment]
#4899 is also experiencing this bug (but lets be honest, who didn't?)

**Comment by Moe-Ronickah** [comment]
Well, as of a couple of days ago, Salted was trying to reproduce this bug in-game.  The bug is still alive.  Reproducing it, and getting a log of just what the heck is happening, is the next step to fixing it.  So, hold tight, everyone, and keep slots open to catch anything that might get kicked off of your class.

**Comment by Ragersgottagame** [comment]
Lost stuff too
https://gyazo.com/bba444d45ee7eb1fedde0001f48014f2
My stats after losing my items
https://gyazo.com/b54ecfff72ddec3d45705988e07cd7f0

**Comment by Moe-Ronickah** [comment]
@Ragersgottagame , I'm sorry, but Wynncraft has a no-refunds policy.

**Comment by Ragersgottagame** [comment]
@Moe-Ronickah Where?

**Comment by YunoFGasai** [comment]
@Ragersgottagame it isn't written anywhere but I can get you proof of a moderator saying it

**Comment by Moe-Ronickah** [comment]
@Ragersgottagame :  Read [this thread](https://forums.wynncraft.com/threads/all-my-items-are-gone.133129/#post-1486975), here.

**Comment by Ragersgottagame** [comment]
@Moe-Ronickah Looks like it's time to quit...

**Comment by YunoFGasai** [comment]
@Ragersgottagame you don't have to quit, its easy to grind the equipment back or get the le to buy it.

**Comment by Moe-Ronickah** [comment]
@Ragersgottagame , I'm sorry if you've decided to quit, however, it is your choice to do so, or not.  If you would take the time to read the issues and threads that you have been pointed to, you will see that by far and by large, people who enjoy playing on an MMORPG take it in stride when a glitch happens.  Wynncraft is NOT a pre-defined game on a CDROM, it is a LIVE game where just about anything can happen.  We have players who have lost stacks of LE due to glitches, and they just keep on going.  I've lost so much armor, and an end-game wand that was given to me, that I don't even try to think about it.  As Yuno said, you can go back to grinding, you can also go to Detlas and ask for help.  There are plenty of us with extra inventory who help out other players all of the time.  I've always treated these bugs as just another challenge, and just going ahead and played.  I like the server, I like the community.  Nothing is going to make me quit.

**Comment by Ragersgottagame** [comment]
@YunoFGasai The problem with buying is that I only have 11le.
@Moe-Ronickah Maybe I'll go back in a month after I'm not salty about it.

**Comment by Trixter313** [comment]
This should be fixed as of patch 14.0.11 ( https://forums.wynncraft.com/threads/patch-14-0-11.135207/ )

**Comment by TheDollarBill** [comment]
Apparently, this bug isn't fixed yet.

https://forums.wynncraft.com/threads/wow-skill-point-glitch-fix-was-all-a-trick.135455/
https://forums.wynncraft.com/threads/i-trusted-you-salted.135607/
https://forums.wynncraft.com/threads/patch-14-0-11.135207/page-3#post-1505499
https://forums.wynncraft.com/threads/patch-14-0-11.135207/page-3#post-1505609
https://forums.wynncraft.com/threads/patch-14-0-11.135207/page-3#post-1505742
https://forums.wynncraft.com/threads/patch-14-0-11.135207/page-6#post-1507191
https://forums.wynncraft.com/threads/patch-14-0-11.135207/page-7#post-1509773

**Comment by Moe-Ronickah** [comment]
It's fixed for armor but not for accessories.  If a piece of armor requires an accessory for skill points, and the accessory pops off, so does the armor.

**Comment by Creeperlover2001** [comment]
this has happened to me, deleted my Morph-Topaz, and my Morph-Amethyst....

**Comment by LordHelmchen98** [comment]
Yeah it's a known bug that still affects accessories as Moe-Ronickah said. Just try to keep one empty inventory slots for every accessory that has skill point requirements.

**Comment by Moe-Ronickah** [comment]
BLAM!!  I lost all four Morph accessories, and I had 5 open slots.  I don't know what's up with that.

**Comment by DebugingLonks** [comment]
Poor you Moe! xD I can actually give you mine if you want... anyway, I have this issue too.

**Comment by DebugMC** [comment]
Happened to me last night, but only on my morph armor... thankfully I found all the parts behind me.

**Comment by 0x0000null** [comment]
Still happening... my Morph-Topaz came off after logging in, causing the rest of armor and accessories to come off.

<img width="979" alt="screen shot 2017-02-03 at 8 27 13 pm" src="https://cloud.githubusercontent.com/assets/16504771/22615698/5addbb12-ea4f-11e6-9b9d-9b31ade6c635.png">

**Comment by Moe-Ronickah** [comment]
After losing two accessories, and two armor pieces that depend on them, I can say only this:

The admin team is aware of this. It will stay open, even with no activity, until it is fixed.
