### ISSUE TITLE
Xp bug on the Stats Website page

### ISSUE THREAD

**Issue by DCM627** [Wynncraft/Issues#5028]
Not sure if this is the right place for this, but I couldn't find any better place, so here I go...

[link](https://wynncraft.com/stats/player/coolcamcraft)
One of my friends seems to have 106% xp on his mage... Someone messed up somewhere... Can someone please explain this and/or fix if possible? I'm stumped. Also, I'm near positive he deleted his mage after Gavel, if that helps at all...

**Comment by DCM627** [comment]
Also, just realized the link doesn't work... Sorry about that. I have no clue how to operate this website. Copying and pasting the link into the search bar thingy at the top of every browser should work, I think.

**Comment by Trixter313** [comment]
Fixed link, you had the link where the text should be and "url" set as the link. =)

Can his player level up properly, or is his in game xp stuck? Also, is his mage indeed level 16? And has he tried leveling up the class to fix the issue? Thanks!

**Comment by DCM627** [comment]
I will ask him. As you can see on his stats page, he hasn't been on for 3 months now. However, I do recall him telling me he was going to delete his Mage, and that may have caused the issue. But otherwise, I'll wait until he replies to me, which may be a while.

**Comment by DCM627** [comment]
I just asked him, and yes, he did delete his Mage after the Gavel update. I do not further understand what caused this issue, but it is still happening.

**Comment by Moe-Ronickah** [comment]
It has been more than 30 days without a response to this issue, or there have been no further reports of this issue, or it is a Minecraft mechanic and not related to WynnCraft.
