### ISSUE TITLE
Place that you can get stuck

### ISSUE THREAD

**Issue by Nevoska** [Wynncraft/Issues#5652]
4 blocks hight hole in the Lion Lair, that you can get stuck
x=943 y=30 z=-2373
http://imgur.com/a/Dz2Eu

**Comment by AckroWynn** [comment]
Fixed!
@Moe-Ronickah

**Comment by Nevoska** [comment]
not fixed...
![2016-08-06_15 03 14](https://cloud.githubusercontent.com/assets/20825228/17460461/0c263c64-5c3e-11e6-82f0-72fbec1acf81.png)

**Comment by Trixter313** [comment]
It's fixed on the build server; It will be fixed on the play servers when the next map update comes.
