### ISSUE TITLE
TOL BOSS

### ISSUE THREAD

**Issue by war-master-9** [Wynncraft/Issues#5848]
When u defeat the Tol boss u get stuck down under the bridge and warrior and assassing cant get up archer can and maybe mage so yea :P. if u say go up the stairs its blocked so yea :P

**Comment by Moe-Ronickah** [comment]
@AckroWynn , any ideas?

**Comment by DebugingLonks** [comment]
@war-master-9 @Moe-Ronickah Walk towards the front of ToL, there is a ladder leading up. 
#6887 is similar

**Comment by DebugMC** [comment]
Also this isn't a quest issue, its a world issue :P

**Comment by AckroWynn** [comment]
It has been fixed a while back.

**Comment by DebugMC** [comment]
@AckroWynn I tried it last night, didn't fix. Also sometimes i get tped way down.
