### ISSUE TITLE
Sand-Swept Tomb | 1st door doesn't open

### ISSUE THREAD

**Issue by SenseiKakashhi** [Wynncraft/Issues#5912]
1. I exchanged my Silverfish keys to the new [Sand-Swept Tomb Key (#0131)]
2. I went to the dungeon and could enter without any problems
3. I did beat two waves of enemys and the boss
4. I recieved the token in form of a head-sized golden block
5. I accedently threw an Emerald in the hopper but after that the token
6. It didnt open
7. tryed it on other servers
8. let myself die to get out of the dungeon

- I did try it two times on other servers without throwing an Emerald in but the door still didnt open
- I would appreciate it if I could recieve a new key and a solution to the problem.

Player Name: SenseiKakashhi (as Mage lvl 50)
Name: Leo (14)

**Comment by Technitrose** [comment]
I have the same problem, wave event works as anticipated and I am able to get the token from the boss guy, but the door doesn't open when I throw it into the hopper. I've tried about 6 times on different servers, and /killed myself then went into the dungeon again, but it was to no avail because it still doesn't work.

**Comment by apeklets** [comment]
https://forums.wynncraft.com/threads/1-14-1-the-gameplay-update-patch-1.147905/ this issue should now be fixed

**Comment by Dystinct** [comment]
#5849

**Comment by Fornax96** [comment]
I'm still having this problem, I've defeated the boss on 5 different servers and tossed the token in the hopper every time but I still can't get through the door.

If an admin is reading this, could you please TP me out, my soul points are low and I don't want to lose items. My in-game name is Fornax96

**Comment by Technitrose** [comment]
lol @apeklets, do you not realize at what time this issue was opened? This issue exists AFTER the 1.14.1 update, because prior to it the boss wave wouldn't spawn at all, now it does but instead now the hopper doesn't work, throwing the coin into it does nothing, as the door doesn't open.

**Comment by Trixter313** [comment]
Duplicate of https://github.com/Wynncraft/Issues/issues/5849
