### ISSUE TITLE
The old keys are still dropping.

### ISSUE THREAD

**Issue by DoctorWhen** [Wynncraft/Issues#5968]
# Delete this line if you've followed the README instructions and searched for a duplicate issue FIRST, and before posting any new issue.
Hello,
I was moving one of my characters from ragni to detlas when I killed a mob, which dropped an old key. 
You may want to fix this and remove keys from mob drops.

**Comment by Moe-Ronickah** [comment]
First, read the instructions for filing an issue.
Second, this has been fixed.

**Comment by Zellnotronus** [comment]
This is not fixed, as I got a Skeleton Key about 30 minutes ago.
![2016-09-03_21 33 48](https://cloud.githubusercontent.com/assets/17558794/18228528/5aa4798a-7220-11e6-9a06-8eb98d040b72.png)
