### ISSUE TITLE
quest "The Lost"

### ISSUE THREAD

**Issue by castle6750** [Wynncraft/Issues#6032]
I am trying to complete the quest "the lost" and have found all five members of the missing crew, but it says that I still have one more to find. I don't have any more letters in my inventory.

Dejol: Ho, adventurer! Have you found the missing members of my crew? If they're not by their red flag, they can't have gotten too far from it, Come back when you have delivered all 5 letters.

Felim: Keep on looking, you still have to deliver those letters to more of us.

Sytis: Keep searching, young one. There are still more members of my loyal crew to deliver the message to.

Yuge; keep searching, looks like you've got to deliver more of those letters.

Ansei; Have you found the rest of the crew yet? Try looking around for flags raised on a pole.

Kofis; Heh, got lost trying to find the rest of the crew, did you? try looking up high for more flags!

**Comment by Moe-Ronickah** [comment]
So, did you follow Kofis' advice, and look up higher in the canyon?

**Comment by castle6750** [comment]
I found the four other members they were talking about, and delivered all the letters I had in my inventory. Is there more members that I have to find, other than the five I have found? Also, will the quest npc's still work that way if I don't have there letter?

**Comment by castle6750** [comment]
Edit: I found the five* other members they were talking about.
There should be six total including the leader.

**Comment by Moe-Ronickah** [comment]
RESOLVED

**Comment by Moe-Ronickah** [comment]
castle6750  Is this issue resolved for you, or is it still open?  I'd like to confirm with you whichever way this is going.
Thanks, in advance.

**Comment by castle6750** [comment]
Moe-Ronickah, it is not resolved. I have not completed the quest. I have not been on in a while, so I can login and try to complete it again. But it was not working last time I tried.
