### ISSUE TITLE
Potion Making

### ISSUE THREAD

**Issue by Ezohn** [Wynncraft/Issues#6437]
So, when I was doing Potion Making on my warrior, I gathered up the 8 mushrooms, gave it to the assistant when this happened... It's not really working at all. I got 8 mushrooms again and gave it again, but he didn't take them and nothing happened. When I go in the boss room, which i can now do, nothing happens. at all. It makes me sad.
![screen shot 2016-10-21 at 7 57 54 pm](https://cloud.githubusercontent.com/assets/22990347/19615572/1c740b10-97cf-11e6-8c33-5aedf586dd8a.png)

**Comment by Trixter313** [comment]
Do you have the dusty coat in your inventory from Essren? Here is the wiki page for the quest, in case it helps: https://wiki.wynncraft.com/index.php?title=Potion_Making

**Comment by oscar725** [comment]
Same to me and we dont have the Dusty coat

**Comment by LordHelmchen98** [comment]
You need to go into the house and defeat Essren. He drops a leather chest called dusty coat which you have to give to the assistant.

**Comment by oscar725** [comment]
i know but he aint ther

**Comment by Trixter313** [comment]
Does Essren appear if you try switching to another world?

**Comment by MercyGRID** [comment]
I too have the same problem. Switching to another world does not correct the issue. He still does not appear.

**Comment by HazardEST** [comment]
i have the same problem

**Comment by BlaupilzHD** [comment]
where the fix i still have the same problem ._.

**Comment by DebugMC** [comment]
I had this problem, but the thing is I could enter I think the the guy doesn't change his message.

**Comment by Moe-Ronickah** [comment]
RESOLVED

**Comment by isaacdare** [comment]
How is this resolved? I see no solution here, and Essren still not not spawn in his house for me.
