### ISSUE TITLE
Mixed feelings - unprogressable 

### ISSUE THREAD

**Issue by Jaka842** [Wynncraft/Issues#7774]
so while doing mixed feelings on my other class, it stopped progressing and won't let me continue. ive already done this quest before so i know what to do so its not just me getting stuck on a certain step :/
so in this quest youre meant to help out 3 citizens in the docks and then you can progress forwards. ive helped out the three citizens, but it only says ive helped two. i went back to check that ive helped them all and it says i have. heres a screenshot of all three saying that ive helped them, and then me trying to progress onwards but being told to help out the citizens
https://gyazo.com/d1b333d6316b7e514548f7072f0d589a
i even went as far as helping all three again but i just get the same results... ?
quest book says that i need to help more citizens for clues

**Comment by AscendedKitten** [comment]
Hey! Would you mind stating what your quest book says? Also, did you get the "hint dialogue" from all npcs? It could be the case that you skipped Javen at the start, if that happened please wait for the bugfix coming asap.

**Comment by Jaka842** [comment]
https://gyazo.com/ebb7f2e7efc66052f3808c01d766930f

thanks for the response, i will be waiting for the bugfix

**Comment by AscendedKitten** [comment]
Hmm, doesn't seem like you missed Javen though; So you got a [x/3] title message after talking to each npc? Did any of them not say something after returning?

**Comment by AscendedKitten** [comment]
Nevermind actually, can you remember if you talked to Javen (the barkeeper) after leaving the cutscene, in the destroyed version of corkus docks, or did you talk to him later?

**Comment by Jaka842** [comment]
[x/3] is just enhanced filtering out duped messages 

i do remember leaving the building before speaking to javen, but i did return to him afterwards

**Comment by Jaka842** [comment]
oh crap yeah i remember talking to the boat npc and then returning back... would that be the cause? if so, would this also be fixed in the patch?

**Comment by AscendedKitten** [comment]
Yeah, that was my bad. The new patch adds a fix for that, so once you relog on an updated server you should be able to re-do the tasks to get the hint from all of them. Sorry!

**Comment by JackyKit123** [comment]
@AscendedKitten it's not fixed
I have the exact same problem as @Jaka842 
I tried redoing the task and /kill restarting from the begging and talked to all NPC and redo the quest on a new server, nothing works

**Comment by JackyKit123** [comment]
@AscendedKitten I tried doing the quest again today
the same problem exists
all 3 tasks are finished, and I tried redoing that again
http://i.imgur.com/1od80qi.png
http://i.imgur.com/ATCkSUu.png
it's not letting me progress or to do the 3 tasks again

**Comment by LordHelmchen98** [comment]
Is this still a problem?
