### ISSUE TITLE
Map glitch

### ISSUE THREAD

**Issue by roythepixel** [Wynncraft/Issues#8596]
I was checking the wynncraft map but my guys marker/head thing didn't show up so I had no idea where i was. Does anyone have a fix?

**Comment by creepeyboy** [comment]
i think im having the same issue, i cant see anyone(myself or friends) on the map

**Comment by thecoolkogut4** [comment]
This is a temporary bug and should be fixed within a few hours

**Comment by creepeyboy** [comment]
im still having the same issue

**Comment by bdvenom** [comment]
I started having this issue on 7/14, and still don't see myself on the map.

**Comment by thecoolkogut4** [comment]
Just give it some time, this will be getting fixed.

**Comment by maxw2000** [comment]
having the same issue
